/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_blog_posts_status = pgEnum('enum_blog_posts_status', ['published', 'draft'])
export const enum_pages_page_type = pgEnum('enum_pages_page_type', [
  'homepage',
  'service',
  'service-area',
  'static',
])
export const enum_pages_status = pgEnum('enum_pages_status', ['published', 'draft'])
export const enum_contact_submissions_service = pgEnum('enum_contact_submissions_service', [
  'tree-removal',
  'tree-trimming',
  'emergency',
  'storm-cleanup',
  'land-clearing',
  'municipal',
  'general',
])
export const enum_contact_submissions_property_type = pgEnum(
  'enum_contact_submissions_property_type',
  ['residential', 'commercial', 'municipal'],
)
export const enum_contact_submissions_urgency = pgEnum('enum_contact_submissions_urgency', [
  'emergency',
  'urgent',
  'standard',
  'planning',
])
export const enum_contact_submissions_preferred_contact = pgEnum(
  'enum_contact_submissions_preferred_contact',
  ['phone', 'email', 'text'],
)
export const enum_contact_submissions_status = pgEnum('enum_contact_submissions_status', [
  'new',
  'contacted',
  'quote-sent',
  'scheduled',
  'completed',
  'declined',
])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts').default('0'),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize'),
    width: numeric('width'),
    height: numeric('height'),
    focalX: numeric('focal_x'),
    focalY: numeric('focal_y'),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const blog_posts_faq = pgTable(
  'blog_posts_faq',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    question: varchar('question').notNull(),
    answer: jsonb('answer').notNull(),
  },
  (columns) => [
    index('blog_posts_faq_order_idx').on(columns._order),
    index('blog_posts_faq_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [blog_posts.id],
      name: 'blog_posts_faq_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const blog_posts = pgTable(
  'blog_posts',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug'),
    content: jsonb('content'),
    excerpt: varchar('excerpt'),
    featuredImage: integer('featured_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    publishedDate: timestamp('published_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    author: varchar('author').default('Jenny B'),
    readingTime: numeric('reading_time'),
    seo_title: varchar('seo_title'),
    seo_description: varchar('seo_description'),
    seo_keywords: varchar('seo_keywords'),
    seo_image: integer('seo_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    status: enum_blog_posts_status('status').default('published'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('blog_posts_slug_idx').on(columns.slug),
    index('blog_posts_featured_image_idx').on(columns.featuredImage),
    index('blog_posts_seo_seo_image_idx').on(columns.seo_image),
    index('blog_posts_updated_at_idx').on(columns.updatedAt),
    index('blog_posts_created_at_idx').on(columns.createdAt),
  ],
)

export const blog_posts_rels = pgTable(
  'blog_posts_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    categoriesID: integer('categories_id'),
    tagsID: integer('tags_id'),
  },
  (columns) => [
    index('blog_posts_rels_order_idx').on(columns.order),
    index('blog_posts_rels_parent_idx').on(columns.parent),
    index('blog_posts_rels_path_idx').on(columns.path),
    index('blog_posts_rels_categories_id_idx').on(columns.categoriesID),
    index('blog_posts_rels_tags_id_idx').on(columns.tagsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [blog_posts.id],
      name: 'blog_posts_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'blog_posts_rels_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: 'blog_posts_rels_tags_fk',
    }).onDelete('cascade'),
  ],
)

export const categories = pgTable(
  'categories',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug'),
    description: varchar('description'),
    color: varchar('color'),
    icon: varchar('icon'),
    featuredImage: integer('featured_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    seo_title: varchar('seo_title'),
    seo_description: varchar('seo_description'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('categories_slug_idx').on(columns.slug),
    index('categories_featured_image_idx').on(columns.featuredImage),
    index('categories_updated_at_idx').on(columns.updatedAt),
    index('categories_created_at_idx').on(columns.createdAt),
  ],
)

export const tags = pgTable(
  'tags',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug'),
    description: varchar('description'),
    color: varchar('color'),
    seo_title: varchar('seo_title'),
    seo_description: varchar('seo_description'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('tags_slug_idx').on(columns.slug),
    index('tags_updated_at_idx').on(columns.updatedAt),
    index('tags_created_at_idx').on(columns.createdAt),
  ],
)

export const pages = pgTable(
  'pages',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug'),
    pageType: enum_pages_page_type('page_type').default('static'),
    content: jsonb('content'),
    excerpt: varchar('excerpt'),
    featuredImage: integer('featured_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    seo_title: varchar('seo_title'),
    seo_description: varchar('seo_description'),
    seo_keywords: varchar('seo_keywords'),
    seo_image: integer('seo_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    publishedDate: timestamp('published_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    status: enum_pages_status('status').default('published'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('pages_slug_idx').on(columns.slug),
    index('pages_featured_image_idx').on(columns.featuredImage),
    index('pages_seo_seo_image_idx').on(columns.seo_image),
    index('pages_updated_at_idx').on(columns.updatedAt),
    index('pages_created_at_idx').on(columns.createdAt),
  ],
)

export const contact_submissions = pgTable(
  'contact_submissions',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    email: varchar('email').notNull(),
    phone: varchar('phone'),
    service: enum_contact_submissions_service('service').default('general'),
    propertyType: enum_contact_submissions_property_type('property_type').default('residential'),
    urgency: enum_contact_submissions_urgency('urgency').default('standard'),
    message: varchar('message'),
    address: varchar('address'),
    preferredContact:
      enum_contact_submissions_preferred_contact('preferred_contact').default('email'),
    bestTimeToCall: varchar('best_time_to_call'),
    status: enum_contact_submissions_status('status').default('new'),
    notes: varchar('notes'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('contact_submissions_updated_at_idx').on(columns.updatedAt),
    index('contact_submissions_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    'blog-postsID': integer('blog_posts_id'),
    categoriesID: integer('categories_id'),
    tagsID: integer('tags_id'),
    pagesID: integer('pages_id'),
    'contact-submissionsID': integer('contact_submissions_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_blog_posts_id_idx').on(columns['blog-postsID']),
    index('payload_locked_documents_rels_categories_id_idx').on(columns.categoriesID),
    index('payload_locked_documents_rels_tags_id_idx').on(columns.tagsID),
    index('payload_locked_documents_rels_pages_id_idx').on(columns.pagesID),
    index('payload_locked_documents_rels_contact_submissions_id_idx').on(
      columns['contact-submissionsID'],
    ),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['blog-postsID']],
      foreignColumns: [blog_posts.id],
      name: 'payload_locked_documents_rels_blog_posts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'payload_locked_documents_rels_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: 'payload_locked_documents_rels_tags_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['pagesID']],
      foreignColumns: [pages.id],
      name: 'payload_locked_documents_rels_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['contact-submissionsID']],
      foreignColumns: [contact_submissions.id],
      name: 'payload_locked_documents_rels_contact_submissions_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_blog_posts_faq = relations(blog_posts_faq, ({ one }) => ({
  _parentID: one(blog_posts, {
    fields: [blog_posts_faq._parentID],
    references: [blog_posts.id],
    relationName: 'faq',
  }),
}))
export const relations_blog_posts_rels = relations(blog_posts_rels, ({ one }) => ({
  parent: one(blog_posts, {
    fields: [blog_posts_rels.parent],
    references: [blog_posts.id],
    relationName: '_rels',
  }),
  categoriesID: one(categories, {
    fields: [blog_posts_rels.categoriesID],
    references: [categories.id],
    relationName: 'categories',
  }),
  tagsID: one(tags, {
    fields: [blog_posts_rels.tagsID],
    references: [tags.id],
    relationName: 'tags',
  }),
}))
export const relations_blog_posts = relations(blog_posts, ({ one, many }) => ({
  faq: many(blog_posts_faq, {
    relationName: 'faq',
  }),
  featuredImage: one(media, {
    fields: [blog_posts.featuredImage],
    references: [media.id],
    relationName: 'featuredImage',
  }),
  seo_image: one(media, {
    fields: [blog_posts.seo_image],
    references: [media.id],
    relationName: 'seo_image',
  }),
  _rels: many(blog_posts_rels, {
    relationName: '_rels',
  }),
}))
export const relations_categories = relations(categories, ({ one }) => ({
  featuredImage: one(media, {
    fields: [categories.featuredImage],
    references: [media.id],
    relationName: 'featuredImage',
  }),
}))
export const relations_tags = relations(tags, () => ({}))
export const relations_pages = relations(pages, ({ one }) => ({
  featuredImage: one(media, {
    fields: [pages.featuredImage],
    references: [media.id],
    relationName: 'featuredImage',
  }),
  seo_image: one(media, {
    fields: [pages.seo_image],
    references: [media.id],
    relationName: 'seo_image',
  }),
}))
export const relations_contact_submissions = relations(contact_submissions, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    'blog-postsID': one(blog_posts, {
      fields: [payload_locked_documents_rels['blog-postsID']],
      references: [blog_posts.id],
      relationName: 'blog-posts',
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: 'categories',
    }),
    tagsID: one(tags, {
      fields: [payload_locked_documents_rels.tagsID],
      references: [tags.id],
      relationName: 'tags',
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: 'pages',
    }),
    'contact-submissionsID': one(contact_submissions, {
      fields: [payload_locked_documents_rels['contact-submissionsID']],
      references: [contact_submissions.id],
      relationName: 'contact-submissions',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_blog_posts_status: typeof enum_blog_posts_status
  enum_pages_page_type: typeof enum_pages_page_type
  enum_pages_status: typeof enum_pages_status
  enum_contact_submissions_service: typeof enum_contact_submissions_service
  enum_contact_submissions_property_type: typeof enum_contact_submissions_property_type
  enum_contact_submissions_urgency: typeof enum_contact_submissions_urgency
  enum_contact_submissions_preferred_contact: typeof enum_contact_submissions_preferred_contact
  enum_contact_submissions_status: typeof enum_contact_submissions_status
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  blog_posts_faq: typeof blog_posts_faq
  blog_posts: typeof blog_posts
  blog_posts_rels: typeof blog_posts_rels
  categories: typeof categories
  tags: typeof tags
  pages: typeof pages
  contact_submissions: typeof contact_submissions
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_blog_posts_faq: typeof relations_blog_posts_faq
  relations_blog_posts_rels: typeof relations_blog_posts_rels
  relations_blog_posts: typeof relations_blog_posts
  relations_categories: typeof relations_categories
  relations_tags: typeof relations_tags
  relations_pages: typeof relations_pages
  relations_contact_submissions: typeof relations_contact_submissions
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
